site_name: Homelab Infrastructure as Code
site_description: Enterprise-grade homelab infrastructure using Terraform, Ansible, and Packer
site_author: Homelab Documentation
repo_url: https://github.com/yourusername/homelab-iac
repo_name: homelab-iac

theme:
  name: material
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Getting Started:
      - Overview: getting-started/overview.md
      - Prerequisites: getting-started/prerequisites.md
      - Quick Start: getting-started/quick-start.md
  - Architecture:
      - Overview: architecture/overview.md
      - Network Design: architecture/network.md
      - Storage Strategy: architecture/storage.md
      - Security Model: architecture/security.md
  - Disaster Recovery:
      - Proxmox DR Script: disaster-recovery/proxmox-dr.md
      - Backup Strategy: disaster-recovery/backup-strategy.md
      - Recovery Procedures: disaster-recovery/recovery-procedures.md
  - Infrastructure:
      - Terraform: infrastructure/terraform.md
      - Ansible: infrastructure/ansible.md
      - Packer: infrastructure/packer.md
  - Services:
      - Control VM: services/control-vm.md
      - Third-Party Apps: services/third-party-apps.md
      - Custom Applications: services/custom-applications.md
  - Operations:
      - Adding a Service: operations/add-service.md
      - Updating VMs: operations/update-vms.md
      - Troubleshooting: operations/troubleshooting.md
  - Migration Guide: migration.md

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yourusername/homelab-iac
